export default (lng) => {
  return `
  query bannerQuery{
    nodeQuery (
      filter:{
             conjunction: AND
              conditions: [{
                field: "type"
                value: ["banner_home"]
             },
             {
                field: "langcode"
                value: ["${lng}"]
              }]
          },
          sort: [{field: "changed", direction: DESC}], limit: 5
    ){
      count,
      entities {
        entityTranslation(language: "${lng}") {
          entityLabel,
          ... on NodeBannerHome {
            fieldSubtitle {
              value
            },
            fieldImage {
              alt,
              url
            },
            fieldCallToAction {
              url{
                alias
              },
              uri,
              title
            }
          }
          
        }
        
        
      } 
    }
  }
  `
}
